# Generated by Django 5.2.8 on 2025-12-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nom complet"
            ),
        ),
    ]
