# Generated by Django 5.2.8 on 2025-12-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_utilisateur_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="type_utilisateur",
            field=models.CharField(
                choices=[("client", "Client"), ("gerant", "Gérant")],
                default="client",
                max_length=10,
            ),
        ),
    ]
