# Generated by Django 5.2.8 on 2025-12-02 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_utilisateur_type_utilisateur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="type_utilisateur",
            field=models.CharField(
                choices=[("client", "Client"), ("gerant", "Gérant")],
                default="client",
                max_length=10,
                verbose_name="Type d'utilisateur",
            ),
        ),
        migrations.CreateModel(
            name="Formule_Abonnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("number_science", models.IntegerField()),
                ("prix_mensuel", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "salle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formules_abonnement",
                        to="app.salle",
                    ),
                ),
            ],
        ),
    ]
