# Generated by Django 5.2.8 on 2025-12-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_verificationcode_is_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationcode",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
