# Generated by Django 5.2.8 on 2025-12-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_verificationcode_is_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gerant",
            name="nif",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="NIF (Numéro d'Identification Fiscale)",
            ),
        ),
    ]
