# Generated by Django 6.0 on 2025-12-05 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_gerant_nif"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoraireOuverture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jourSemaine",
                    models.CharField(
                        choices=[
                            ("LUNDI", "Lundi"),
                            ("MARDI", "Mardi"),
                            ("MERCREDI", "Mercredi"),
                            ("JEUDI", "Jeudi"),
                            ("VENDREDI", "Vendredi"),
                            ("SAMEDI", "Samedi"),
                            ("DIMANCHE", "Dimanche"),
                        ],
                        max_length=10,
                    ),
                ),
                ("heureOuverture", models.TimeField()),
                ("heureFermeture", models.TimeField()),
                ("estFerme", models.BooleanField(default=False)),
                (
                    "salle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horaires_ouverture",
                        to="app.salle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horaire d'Ouverture",
                "verbose_name_plural": "Horaires d'Ouverture",
                "unique_together": {("salle", "jourSemaine")},
            },
        ),
    ]
