# Generated by Django 5.2.8 on 2025-12-03 02:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_gerant_nif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('yoga', 'Yoga'), ('hiit_burn', 'HIIT Burn'), ('indoor_cycling', 'Indoor Cycling'), ('barbell_basics', 'Barbell Basics'), ('crossfit', 'CrossFit'), ('pilates', 'Pilates')], max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('all_levels', 'All Levels')], max_length=20)),
                ('duration_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('duration_unit', models.CharField(choices=[('min', 'Minutes'), ('hour', 'Hours')], default='min', max_length=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app.salle')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('salle', 'name', 'level')},
            },
        ),
    ]
