# Generated by Django 5.2.8 on 2025-12-11 15:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_horaireouverture'),
    ]

    operations = [
        migrations.CreateModel(
            name='concerneEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_etoile', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('SalleEquipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concernes', to='app.salleequipement')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concernes_equipements', to='app.client')),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concernes_equipements', to='app.criterenotation')),
            ],
            options={
                'unique_together': {('critere', 'SalleEquipement', 'client')},
            },
        ),
    ]
