# Generated by Django 5.2.8 on 2025-12-03 12:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SallePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='salles/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('photo_type', models.CharField(choices=[('cover', 'Photo de couverture'), ('profile', 'Photo de profil'), ('gallery', 'Galerie')], default='gallery', max_length=10)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans la galerie (0 = premier)")),
                ('legende', models.CharField(blank=True, help_text='Description de la photo (optionnel)', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app.salle')),
            ],
            options={
                'verbose_name': 'Photo de salle',
                'verbose_name_plural': 'Photos de salles',
                'ordering': ['ordre', '-uploaded_at'],
            },
        ),
    ]
