# Generated by Django 5.2.8 on 2025-12-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_concerneservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
