# Generated by Django 5.2.8 on 2025-12-03 13:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_sallephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sallephoto',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
