# Generated by Django 5.2.8 on 2025-12-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_horaireouverture'),
        ('app', '0012_alter_sallephoto_image'),
    ]

    operations = [
    ]
