# Generated by Django 5.2.8 on 2025-12-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_salle_views_count'),
        ('app', '0013_merge_20251211_1449'),
    ]

    operations = [
    ]
