# Generated by Django 5.2.8 on 2025-12-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_salle_latitude_alter_salle_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='nom',
            field=models.CharField(choices=[('douchessssssSSSSSs', 'DouchesSSSSSSSSS'), ('douches', 'Douches'), ('wifi', 'Wifi'), ('climatisation', 'Climatisation'), ('parking', 'Parking')], max_length=50, unique=True),
        ),
    ]
