# Generated by Django 5.2.8 on 2025-12-19 16:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_service_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcerneCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_etoile', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concernes_courses', to='app.client')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concernes', to='app.course')),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concernes_courses', to='app.criterenotation')),
            ],
            options={
                'unique_together': {('critere', 'course', 'client')},
            },
        ),
    ]
