# Generated by Django 5.2.8 on 2025-12-24 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_concernecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='note_equipement',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='avis',
            name='note_globale',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='avis',
            name='note_personnel',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='avis',
            name='note_proprete',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='avis',
            name='note_rapport_qualite_prix',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
